_site/config/routes.rb
Saveitforlater::Application.routes.draw do
  root 'static_pages#home'

  resources :users
  resources :memos, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  

  
end

_site/app/models/memo.rb
class Memo < ActiveRecord::Base
  belongs_to :user
  validates :info, presence: true, length: { maximum: 160 }
  validates :link, presence: true, length: { maximum: 2000 }
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true

  self.per_page = 10
end

_site/app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.username = username.downcase }
  
  has_many :memos, dependent: :destroy

  validates :username, presence: true, uniqueness: true
  validates :name, length: { maximum: 200 } 

  has_secure_password
  validates :password, length: { minimum: 6 }


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

   def feed
    Memo.where("user_id = ?", id)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

_site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

_site/app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  # GET /memos
  # GET /memos.json
  def index
    redirect_to root_url
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
    @memos = Memo.paginate(page: params[:page], per_page: 15)
  end

  # GET /memos/new
  def new
    @memo = Memo.new
    redirect_to root_url
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = current_user.memos.build(memo_params)

      if @memo.save
        flash[:success] = "Memo created!"
        
      else
        # @feed_items = []
        @memo.errors.full_messages.join('. ')
      end

      redirect_to root_url
  end

  # PATCH/PUT /memos/1
  # PATCH/PUT /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to @memo, notice: 'Memo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo.destroy
   redirect_to root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      @memo = Memo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memo_params
      params.require(:memo).permit(:info, :link)
    end

    def correct_user
      @memo = current_user.memos.find_by(id: params[:id])
      redirect_to root_url if @memo.nil?
    end
end

_site/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to root_url
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_url
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

_site/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @memo = current_user.memos.build
      @feed_items = current_user.feed
    end
  end

  def about
  end

  def contact
  end
end

_site/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    redirect_to root_url
  end

  # GET /users/1
  # GET /users/1.json
  def show
    redirect_to root_url
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Save it for Later!"
      redirect_to root_url
    else
      flash[:error] = "Whoops! Looks like some errors in your info"
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :username, :password, :password_confirmation)
    end
end

_site/app/helpers/application_helper.rb
module ApplicationHelper
end

_site/app/helpers/memos_helper.rb
module MemosHelper
end

_site/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to root_url, notice: "Please sign in."
    end
  end

  def current_user?(user)
    user == current_user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

end

_site/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

_site/app/helpers/users_helper.rb
module UsersHelper
end

_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>&amp; save it for later</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,700,900,200italic,400italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500' rel='stylesheet' type='text/css'>

</head>
<body>
  <div class="container">
    <div class="header">
      <h1> &amp; save it for later </h1>
      <nav>
        
        <ul>
          <% if signed_in? %>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Home", root_url %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><%= link_to "Register", signup_path %></li>
          <% end %>
        </ul>  
      </nav>
    </div>

    <%= yield %>

  </div>
</body>
</html>

_site/app/views/memos/edit.html.erb
<h1>Editing memo</h1>

<%= render 'form' %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

_site/app/views/memos/index.html.erb
<h1>Listing memos</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Info</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td><%= memo.link %></td>
        <td><%= memo.info %></td>
        <td><%= memo.user_id %></td>
        <td><%= link_to 'Show', memo %></td>
        <td><%= link_to 'Edit', edit_memo_path(memo) %></td>
        <td><%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memo', new_memo_path %>

_site/app/views/memos/new.html.erb
<h1>New memo</h1>

<%= render 'form' %>

<%= link_to 'Back', memos_path %>

_site/app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @memo.link %>
</p>

<p>
  <strong>Info:</strong>
  <%= @memo.info %>
</p>

<p>
  <strong>User:</strong>
  <%= @memo.user_id %>
</p>

<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>

_site/app/views/static_pages/about.html.erb
<div class="about">
  <h2>the idea</h2>
  <p>I've been in the pickle a lot lately where I have a link on one computer or my phone, and I want to save it so I can look at it at home on my own computer. I don't want to go through the hassle of opening up my email and emailing it to myself, or posting it on my facebook so "only me" can see it. I want them all amalgamated somewhere I can go to and take a look. </p>

  <p>I've also been in the predicament where I will have some tabs open for something to read later when I come to the topic, but don't want to keep them open because I'm running out of tab room. What can I do with it? Copy the link somewhere so I can access it later. Except I haven't signed up for something like Pocket because I don't want it on a reading list, I just want to look at it later.</p>

  <p>I like to think that everyone has been in this situation before, and this is my solution.</p>


  <h2>the implementation</h2>
  <p>The idea is simple. All you do is paste your link, give it a title for context and press save and it's in your list! Easy peasy. Since it's only one page, there's no chance of getting lost or losing links. All your links for later or in a couple days are listed, easily accessible and in a list sorted by when you added them.</p>

  <p>The design is also minimalistic so that nothing gets in the way, you don't need anything flashy to list some links, on a page you're just using for going to other pages anyway. Why make it complicated?</p>


</div>  

_site/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

_site/app/views/static_pages/home.html.erb
<!-- provide title -->
<% if signed_in? %>
  <div class="sidebar">

    <p class="username"> <%= current_user.username %></p>

    <p class="memo-form-title">Bookmark a link</p>
    <%= render 'shared/memo_form' %>
     

  </div>
  <div class="main">
    <!-- <h2>links</h2> -->
    <% if current_user.memos.count == 0 %>
      <p>No links found here! You must have some stashed away you can't get to yet...right?</p>
    <% else %>
      <%= render 'shared/feed' %>
    <% end %>

  </div>

<% else %>
    
  <div class="signin-welcome-message">
    <div class="prelim-message">
      <h2>welcome.</h2>
      <p>
        Sometimes I'll be on a different computer, have too many tabs open on a different subject or just want to look at something later. Wouldn't it be nice to have a simple place you can just paste a link, give some context and leave it for yourself when you have time? That's exactly what this website is for, your links on your own time.
      </p>
    </div>
    <div class="signin-form">
      <%= form_for(:session, url: sessions_path) do |f| %>
      <%= f.text_field :username, placeholder: "Username", class: "signin-field" %><br>
      <%= f.password_field :password, placeholder: "Password", class: "signin-password signin-field" %><br>
      <%= f.submit "begin", class: "signin-submit" %>
    </div>
    <% end %>

</div>

<% end %>

_site/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

_site/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Username</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

_site/app/views/users/new.html.erb
<div class="signup-welcome-message">
  <h2>register and join the fun.</h2>

  <%= render 'form' %>
</div>

_site/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>


<div class="span8">
    <% if @user.memos.any? %>
      <h3>Memos (<%= @user.memos.count %>)</h3>
      <ol class="microposts">
        <%= render @memos %>
      </ol>
    <% end %>
  </div>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>